sudo: false

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - happy-1.19.5
    - alex-3.1.7
    - ghc-$GHCVER
    - cabal-install-$CABALVER

env: CABALVER=1.18 GHCVER=7.6.3
env: CABALVER=1.18 GHCVER=7.8.4
env: CABALVER=head GHCVER=head

allow_failures:
 - env: CABALVER=head GHCVER=head
 - env: CABALVER=1.24 GHCVER=8.0.1 # GHC bug 11458

script:
 - export HAPPYVER=1.19.5
 - export ALEXVER=3.1.7
 - export PATH=~/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/$HAPPYVER/bin:/opt/alex/$ALEXVER/bin:$PATH
 - cabal --version
 - ghc --version
