sudo: false
language: generic

addons: {apt: {packages: [happy-1.19.5, alex-3.1.7], sources: [hvr-ghc]}}

matrix:
  include:
    - env: GHCVER=7.6.3
      addons: {apt: {packages: [ghc-7.6.3,cabal-install-1.18], sources: [hvr-ghc]}}
    - env: GHCVER=HEAD
      addons: {apt: {packages: [ghc-head,cabal-install-head], sources: [hvr-ghc]}}

  allow_failures:
   - env: GHCVER=HEAD

# Note: script continues if there is a failure, install does not
# When using for real should use 'install'
script:
 - export PATH=~/.cabal/bin:/opt/ghc/$(ls /opt/ghc)/bin:/opt/cabal/$(ls /opt/cabal)/bin:/opt/happy/$(ls /opt/happy)/bin:/opt/alex/$(ls /opt/alex)/bin:$PATH
 - ls /opt/ghc
 - ls /opt/cabal
 - ls /opt/happy
 - ls /opt/alex
 - cabal --version
 - ghc --version
 - happy --version
 - alex --version
